### ISSUE TITLE
Note that AS::Duration.new API differs from ActiveSupport::Duration.new API

### ISSUE THREAD

**Issue by jeremyevans** [janko-m/as-duration#3]
I was looking into optionally using `AS::Duration` instead of `ActiveSupport::Duration` for Sequel's `pg_interval` extension, but I found the constructors for the two classes are different, so it is not possible to simply swap `ActiveSupport::Duration` for `AS::Duration`.  This difference isn't mentioned in the README, and it probably should be, since the README gives the impression that the 'AS::Duration` is compatible except in cases listed explicitly.

Alternatively, you may want to support `ActiveSupport::Duration's` constructor API. That would increase compatibility.

**Comment by janko** [comment]
Thank you for reporting this. For some reason I assumed that no one would be instantiating ActiveSupport::Duration directly, and later I forgot to mention it in the readme. There was no good reason to change it, I could easily just keep ActiveSupport's one. I released version 0.1.0 with the fix.
